[2023-05-06 20:21:10,430] root - INFO - Training pipleine config: TrainingPipelineConfig(artifact_dir='C:\\Users\\Admin\\Documents\\Shipment_pricing_Project\\shipment\\artifact')
[2023-05-06 20:21:10,430] root - INFO - Data Ingestion config: DataIngestionConfig(dataset_download_url='https://raw.githubusercontent.com/Hitesh-Nimbalkar/Shipment_Pricing_EDA/main/SCMS_Delivery_History_Dataset.csv', raw_data_dir='C:\\Users\\Admin\\Documents\\Shipment_pricing_Project\\shipment\\artifact\\data_ingestion\\2023-05-06-20-21-05\\raw_data', ingested_train_dir='C:\\Users\\Admin\\Documents\\Shipment_pricing_Project\\shipment\\artifact\\data_ingestion\\2023-05-06-20-21-05\\ingested_data\\train', ingested_test_dir='C:\\Users\\Admin\\Documents\\Shipment_pricing_Project\\shipment\\artifact\\data_ingestion\\2023-05-06-20-21-05\\ingested_data\\test')
[2023-05-06 20:21:10,430] root - INFO - >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>Data Ingestion log started.<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< 


[2023-05-06 20:21:10,430] root - INFO - Downloading file from :[https://raw.githubusercontent.com/Hitesh-Nimbalkar/Shipment_Pricing_EDA/main/SCMS_Delivery_History_Dataset.csv] into :[C:\Users\Admin\Documents\Shipment_pricing_Project\shipment\artifact\data_ingestion\2023-05-06-20-21-05\raw_data\SCMS_Delivery_History_Dataset.csv]
[2023-05-06 20:21:10,454] root - ERROR - 
        Error occured in script: [C:\Users\Admin\Documents\Shipment_pricing_Project\Shipment_Pricing\pipeline\pipeline.py] at 
        line number: [87] 
        error message: [
        Error occured in script: [C:\Users\Admin\Documents\Shipment_pricing_Project\Shipment_Pricing\pipeline\pipeline.py] at 
        line number: [36] 
        error message: [
        Error occured in script: [C:\Users\Admin\Documents\Shipment_pricing_Project\Shipment_Pricing\components\data_ingestion.py] at 
        line number: [109] 
        error message: [
        Error occured in script: [C:\Users\Admin\Documents\Shipment_pricing_Project\Shipment_Pricing\components\data_ingestion.py] at 
        line number: [42] 
        error message: [<urlopen error [Errno 11001] getaddrinfo failed>]]]]
